### PR TITLE
Amend `check-ecs-service-health`

### PR DESCRIPTION
**Pull request by marckysharky**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

- [x] Tests

- [x] Add the plugin to the README

- [x] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Known Compatablity Issues

- Collect all services for given cluster

### CODE REVIEW

**Comment by eheydrick** [comment]
Can you add an entry to CHANGELOG for this. Also, I'm not sure why but the ruby 2.2 build is failing. I will try to figure out what's up with that.

**Comment by marckysharky** [comment]
Will add the change log this morning.

Was a strange error in Travis, I'll take a look too, if you don't get there
first.

M

**Comment by marckysharky** [comment]
It seems the issue raised in Travis has been documented, and fixed in Ruby 2.2.1

https://github.com/lsegal/yard/issues/825

**Comment by marckysharky** [comment]
Tests pass, but https://github.com/sensu-plugins/sensu-plugins-aws/pull/131/commits/1f769c745275fbc1f30377f92f9b2f79681ae27d may want to be extracted into a different PR. 

Let me know what you'd prefer.

**Pull request merged**
