### PR TITLE
change mertics elb to read all metrics of the elb

### PR DESCRIPTION
**Pull request by phoppe93**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by phoppe93** [comment]
@sstarcher i changed the metrics-elb. delete the option metric and add a full reading elb metrics 

please merge

**Comment by sstarcher** [comment]
Can you add back the ELB name as an optional parameter to not remove functionality.  When the name is not specified grab all metrics.

Can you also fully reset your repo to the head of this repo.  Your repo says it's 28 commits ahead.

**Comment by phoppe93** [comment]
@sstarcher i add the option elb_name

Frok is already up to date

git remote add upstream git://github.com/sensu-plugins/sensu-plugins-aws.git
git fetch upstream 
From git://github.com/sensu-plugins/sensu-plugins-aws
 * [new branch]      master     -> upstream/master
 * [new tag]         3.2.0      -> 3.2.0
 * [new tag]         3.2.1      -> 3.2.1
git merge upstream/master master
Already up-to-date.

**Comment by sstarcher** [comment]
@phoppe93 the oddity is github it thinks you are 30 commits ahead

https://github.com/phoppe93/sensu-plugins-aws/

**Pull request closed without merging**
