### PR TITLE
Move to aws-sdk-v1 gem to fix issues with ruby2+

### PR DESCRIPTION
**Pull request by pmvilaca**
Issue: #14

### CODE REVIEW

**Comment by tas50** [comment]
We should eventually move to the new version but this is a good fix for now

**Comment by mattyjones** [comment]
@tas50 If you want to throw something on trello under the backlog or here in Issues and set a milestone or whatnot go right ahead so we don't forget about it.

**Comment by pmvilaca** [comment]
@tas50 @mattyjones I think that if we use github issues of each repo, it would help more people to understand the status and future plans for each plugin. 
Anyway, if you want to define a milestone that involves more than one plugin, a central place with the backlog for that milestone would be useful. 

How are you planning to do it. What do you think about organising a meeting on irc to discuss these topics?

**Comment by mattyjones** [comment]
@pmvilaca 

I will make formal announcements as I can but for now here you go.
https://trello.com/b/QjkJ8CS3/sensu-community-plugins  <-- major projects and initiatives(open to the public)

I am a FRIM

**Comment by pmvilaca** [comment]
@mattyjones @tas50 - Sounds good! I sent you an email with some thoughts. 

> By Milestone I would create one for just this plugin. I know it needs a LOT of love. I have rewritten many of these into Python using boto previously but want to keep it in Ruby for now and going forward.

So, in the future each repo will have its own release and ideally, milestones to group some improvements for a release instead of a new release for each change in the master branch? Btw, each repo has its own maintainer or you're in charge of all the plugins?

**Comment by sensu-plugin** [comment]
**So, in the future each repo will have its own release and ideally, milestones to group some improvements for a release instead of a new release for each change in the master branch?**

Yes, each repo is independently versions and maintained.  There may be some cross talk between them but each will have its own lifecycle. 

 **Btw, each repo has its own maintainer or you're in charge of all the plugins?**

I am in change of nothing :)  One of the thoughts on this would be that all the committers maintain all the repos as a whole.  With that being said many of the repos require specific skills, such as aws, elasticsearch, couchbase,etc and the people relying upon and using those plugins now it best.  In short those closest to the code with the most to gain/lose should be the ones maintaining it.

Due to the permissions structure of the org is is hard to bring someone in and only give them access to specific repos but within the metadata they may designate themselves via email or gh handle as 'responsible'.  If over time they have proven they can be trusted and have made significant contributions then they will be brought in as a full committer.

I will be writing docs about all of this and releasing them over the next few weeks as we get ready to soft freeze the orginial repo on July6.

**Pull request merged**
