### PR TITLE
Add check-cloudwatch-alarms

### PR DESCRIPTION
**Pull request by obazoud**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [x] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by sstarcher** [comment]
Does check-cloudwatch-alarm.rb essentially provide the same support?

**Comment by majormoses** [comment]
@obazoud I have not inspected the code deep enough but from what I see we should enhance the existing check to support supplying multiple via an option and/or filter rather than make a new check. Open to discussion and might be missing something obvious.

**Comment by obazoud** [comment]
check-cloudwatch-alarm checks only one alarm.
check-cloudwatch-alarms checks all alarms except exclude alarms.

**Comment by majormoses** [comment]
@obazoud I understand that, but that could be parameter driven rather than a whole new check, seems like a lot of code duplication.

**Comment by majormoses** [comment]
@obazoud I have not heard back from you and while I would prefer a parameter based approach I will accept this if you do a rebase to fix conflicts.

**Comment by majormoses** [comment]
@obazoud I rebased and fixed up the changelog.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-aws/versions/6.3.0

**Pull request merged**
