### PR TITLE
Added RDS connection check

### PR DESCRIPTION
**Pull request by jmccarty3**
Added RDS Connection check and the db.t2.large size to the memory lookup table.

### CODE REVIEW

**Comment by eheydrick** [comment]
Thanks @jmccarty3! Can you add connections to the usage.

**Comment by jmccarty3** [comment]
@eheydrick Added an entry for in usage for connections.

**Comment by eheydrick** [comment]
@jmccarty3 thanks, looks good. One more thing, can you update the changelog.

**Comment by jmccarty3** [comment]
@eheydrick  Updated. I always for get about that

**Comment by eheydrick** [comment]
Thanks, merged.

**Pull request merged**
