### PR TITLE
Add plugin for checking EC2 instance status

### PR DESCRIPTION
**Pull request by eheydrick**

### CODE REVIEW

**Comment by eheydrick** [comment]
Ruby 1.9.3 tests are failing due to net-ssh and fog-google dropping ruby < 2.0 support. https://github.com/fog/fog-core/issues/162

We'll need to either pin to older versions or consider dropping 1.9.3 support.

**Comment by mattyjones** [comment]
@eheydrick @tas50 @analytically  What are thoughts on this. I don't want to drop a supported version but......

**Comment by tas50** [comment]
It's probably time to assume 2.X in the omnibus installer

**Comment by eheydrick** [comment]
I'm in favor of dropping it. 1.9.3 is EOL as of February.

**Comment by analytically** [comment]
:+1: for dropping.

**Comment by eheydrick** [comment]
Think we can merge this now that we've dropped 1.9.3 from the tests. Someone want to review and merge.

**Comment by eheydrick** [comment]
Going to close this and reopen a new one w/o merge conflicts.

**Pull request closed without merging**
