### PR TITLE
Fixed ~10 rubocop offenses and rspec failure when environment unclean.

### PR DESCRIPTION
**Pull request by willbuckner**
When running `rake` on my Macbook with AWS keys configured in environment variables, tests fail and there are many Rubocop offenses. I fixed several of these issues. I can't fix ALL of the Rubocop offenses as my Ruby knowledge is not sufficient to know whether or not it should be followed :)

### CODE REVIEW

**Comment by zbintliff** [comment]
Just wondering what is in your `.rubocop.yml` and if you are overriding those settings at all?  Currently the project builds with no warnings. As shown in the latest PR (https://travis-ci.org/sensu-plugins/sensu-plugins-aws/jobs/103182329#L226)

The sanitation in the rake file is nice though.

**Comment by willbuckner** [comment]
Very interesting. My `.rubocop.yml` is exactly what's checked into `master`:

    MethodLength:
        Max: 200

    LineLength:
        Max: 225

    AbcSize:
      Max: 125

    FileName:
        Enabled: false

    PerceivedComplexity:
        Enabled: false

    CyclomaticComplexity:
        Enabled: false

    ClassLength:
        Enabled: false

    IfUnlessModifier:
        Enabled: false

    RegexpLiteral:
      Enabled: false

    Style/Documentation:
      Enabled: false
    
    Style/Next:
      Enabled: false
    
    Style/FormatString:
      Enabled: false

Using `rubocop 0.36.0` on Mac OS X. Even with my fixes, I still get:

    $ rake
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I/Library/Ruby/Gems/2.0.0/gems/rspec-support-3.4.1/lib:/Library/Ruby/Gems/2.0.0/gems/rspec-core-3.4.1/lib /Library/Ruby/Gems/2.0.0/gems/rspec-core-3.4.1/exe/rspec test/bin/check_certifcate_expiry_spec.rb

	CheckCertificateExpiry
	  #aws_config
	    should return only region
	  #aws_client
	    should return a client
	    should return a client with west region
	  #get_cert
	    should return metadata
	  #check_expiry
	    should not trigger warnings or criticals
	    should trigger warning flag
	    should trigger critical flag
	    should trigger only critflag
	  #run
	    should run and exit ok when passed nothing
	    should run and exit with warning when nothing is passed
	    should run and exit with critical when nothing is passed
	    should run and exit with critical when nothing is passed and both critical and warning are passed
	    should run and exit ok when name is passed
	    should run and exit with warning when name is passed
	    should run and exit with critical when name is passed
	    should run and exit with critical when name is passed and both critical and warning are true

	Finished in 0.31983 seconds (files took 0.40851 seconds to load)
	16 examples, 0 failures

	Files:          42
	Modules:         5 (    3 undocumented)
	Classes:        34 (   33 undocumented)
	Constants:       4 (    4 undocumented)
	Methods:       167 (  160 undocumented)
	 4.76% documented
	Running RuboCop...
	Inspecting 51 files
	.CCC.C..CC..CC...C.C.CCC..C.CC...C.CCCC.CC.CC......

	Offenses:

	Rakefile:12:17: C: Freeze mutable objects assigned to constants.
	  OTHER_PATHS = %w()
	                ^^^^
	sensu-plugins-aws.gemspec:37:59: C: Use String#end_with? instead of a regex match anchored to the end of the string.
	  s.signing_key            = File.expand_path(pvt_key) if $PROGRAM_NAME =~ /gem\z/
	                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
	bin/check-autoscaling-cpucredits.rb:119:31: C: Add parentheses to nested method call statistics_options.merge unit: 'Count'.
	    value = metric.statistics(statistics_options.merge unit: 'Count')
	                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/check-certificate-expiry.rb:92:7: C: Use the return of the conditional for variable assignment and comparison.
	      if time_to_expiry < 1
	      ^^^^^^^^^^^^^^^^^^^^^
	bin/check-dynamodb-capacity.rb:135:23: C: Add parentheses to nested method call statistics_options.merge unit: 'Count'.
	    metric.statistics(statistics_options.merge unit: 'Count').datapoints.sort_by { |datapoint| datapoint[:timestamp] }.last[config[:statistics]]
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/check-dynamodb-throttle.rb:130:23: C: Add parentheses to nested method call statistics_options.merge unit: 'Count'.
	    metric.statistics(statistics_options.merge unit: 'Count').datapoints.sort_by { |datapoint| datapoint[:timestamp] }.last[config[:statistics]]
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/check-ec2-filter.rb:110:5: C: Use the return of the conditional for variable assignment and comparison.
	    if filter.empty?
	    ^^^^^^^^^^^^^^^^
	bin/check-ec2-network.rb:111:31: C: Add parentheses to nested method call statistics_options.merge unit: 'Bytes'.
	    value = metric.statistics(statistics_options.merge unit: 'Bytes')
	                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/check-elb-health-sdk.rb:95:5: C: Use the return of the conditional for variable assignment and comparison.
	    if config[:instances]
	    ^^^^^^^^^^^^^^^^^^^^^
	bin/check-elb-latency.rb:126:23: C: Add parentheses to nested method call statistics_options.merge unit: 'Seconds'.
	    metric.statistics(statistics_options.merge unit: 'Seconds').datapoints.sort_by { |datapoint| datapoint[:timestamp] }.last[config[:statistics]]
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/check-elb-sum-requests.rb:118:23: C: Add parentheses to nested method call statistics_options.merge unit: 'Count'.
	    metric.statistics(statistics_options.merge unit: 'Count').datapoints.sort_by { |datapoint| datapoint[:timestamp] }.last[:sum]
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/check-emr-cluster.rb:109:7: C: Use aws_config[:access_key_id] = config[:aws_access_key]; aws_config[:secret_access_key] = config[:aws_secret_access_key] instead of `aws_config.merge!(
	        access_key_id: config[:aws_access_key],
	        secret_access_key: config[:aws_secret_access_key]
	      )`.
	      aws_config.merge!(
	      ^^^^^^^^^^^^^^^^^^
	bin/check-instance-events.rb:75:7: C: Use aws_config[:access_key_id] = config[:aws_access_key]; aws_config[:secret_access_key] = config[:aws_secret_access_key] instead of `aws_config.merge!(
	        access_key_id: config[:aws_access_key],
	        secret_access_key: config[:aws_secret_access_key]
	      )`.
	      aws_config.merge!(
	      ^^^^^^^^^^^^^^^^^^
	bin/check-rds.rb:158:32: C: Add parentheses to nested method call statistics_options.merge unit: unit.
	    values = metric.statistics(statistics_options.merge unit: unit).datapoints.sort_by { |datapoint| datapoint[:timestamp] }
	                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/check-s3-bucket.rb:73:7: C: Use aws_config[:access_key_id] = config[:aws_access_key]; aws_config[:secret_access_key] = config[:aws_secret_access_key] instead of `aws_config.merge!(
	        access_key_id: config[:aws_access_key],
	        secret_access_key: config[:aws_secret_access_key]
	      )`.
	      aws_config.merge!(
	      ^^^^^^^^^^^^^^^^^^
	bin/check-s3-object.rb:104:7: C: Use aws_config[:access_key_id] = config[:aws_access_key]; aws_config[:secret_access_key] = config[:aws_secret_access_key] instead of `aws_config.merge!(
	        access_key_id: config[:aws_access_key],
	        secret_access_key: config[:aws_secret_access_key]
	      )`.
	      aws_config.merge!(
	      ^^^^^^^^^^^^^^^^^^
	bin/check-vpc-vpn.rb:68:7: C: Use aws_connection_config[:access_key_id] = config[:access_key]; aws_connection_config[:secret_access_key] = config[:secret_key] instead of `aws_connection_config.merge!(
	        access_key_id: config[:access_key],
	        secret_access_key: config[:secret_key]
	      )`.
	      aws_connection_config.merge!(
	      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/handler-ses.rb:85:5: C: Use the return of the conditional for variable assignment and comparison.
	    if @event['check']['notification'].nil?
	    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/handler-sns.rb:47:5: C: Use the return of the conditional for variable assignment and comparison.
	    if template_file && File.readable?(template_file)
	    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/handler-sns.rb:78:7: C: Move t.publish("#{subject} - #{message}", options) out of the conditional.
	      t.publish("#{subject} - #{message}", options)
	      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/handler-sns.rb:82:7: C: Move t.publish("#{subject} - #{message}", options) out of the conditional.
	      t.publish("#{subject} - #{message}", options)
	      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	bin/metrics-autoscaling-instance-count.rb:71:5: C: Use the return of the conditional for variable assignment and comparison.
	    if config[:scheme] == ''
	    ^^^^^^^^^^^^^^^^^^^^^^^^
	bin/metrics-ec2-count.rb:84:9: C: Use the return of the conditional for variable assignment and comparison.
	        if status[stat].nil?
	        ^^^^^^^^^^^^^^^^^^^^
	bin/metrics-ec2-count.rb:112:9: C: Use the return of the conditional for variable assignment and comparison.
	        if data[type].nil?
	        ^^^^^^^^^^^^^^^^^^
	bin/metrics-elasticache.rb:95:5: C: Use the return of the conditional for variable assignment and comparison.
	    if config[:scheme] == ''
	    ^^^^^^^^^^^^^^^^^^^^^^^^
	bin/metrics-elb-full.rb:120:9: C: Use the return of the conditional for variable assignment and comparison.
	        if config[:scheme] == ''
	        ^^^^^^^^^^^^^^^^^^^^^^^^
	bin/metrics-sqs.rb:71:5: C: Use the return of the conditional for variable assignment and comparison.
	    if config[:scheme] == ''
	    ^^^^^^^^^^^^^^^^^^^^^^^^
	lib/sensu-plugins-aws/cloudwatch-common.rb:21:5: C: Use a guard clause instead of wrapping the code inside a conditional expression.
	    elsif compare_method == 'not'
	    ^^^^^

	51 files inspected, 28 offenses detected
	RuboCop failed!
	$

**Comment by zbintliff** [comment]
Can you do the following inside project directory may need sudo for gem install depending on how you have it set up:
```
$ gem install bundler
$ bundle install --path .bundle 
$ bundle exec rake
```
Pretty much what bundle does is make all the dependencies local (sort of like NPM if your familiar with that, or VIrutalEnv with Python)

**Comment by analytically** [comment]
Rebase is possible?

**Comment by sstarcher** [comment]
ping

**Pull request closed without merging**
