### PR TITLE
Trusted Advisor service limits check

### PR DESCRIPTION
**Pull request by swibowo**
AWS implements service limits which governs the allowance to spawn
services.

This plugin uses Trusted Advisor API to perform check for
service limits. Trigger 'critical' on sensu for services
that are not 'Green'.

IAM requires AWSSupportAccess policy enabled.

https://aws.amazon.com/premiumsupport/ta-faqs/

### CODE REVIEW

**Comment by sstarcher** [comment]
* Add execute permissions to the .rb file
* Could you convert it to use aws-sdk v2 instead of aws-sdk-v1
* Could you remove the arguments for aws secret and key and include the Common functions and remove the aws_config block similar to `https://github.com/sensu-plugins/sensu-plugins-aws/blob/master/bin/check-ebs-snapshots.rb`
* You have a few rubocop errors

**Comment by sstarcher** [comment]
Thanks

**Comment by swibowo** [comment]
Trusted advisor does a bunch of checks and audits automatically. Each of these checks/audits have their own check_id.

The check_id is hardcoded because this check is purely for service limits. 

Please refer to documentation here: https://aws.amazon.com/premiumsupport/ta-iam/

**Comment by sstarcher** [comment]
@swibowo thanks again

**Pull request merged**
