### PR TITLE
Creating a method that allows using this sensu check using an IAM rat…

### PR DESCRIPTION
**Pull request by stack72**
…her than keys

### CODE REVIEW

**Comment by analytically** [comment]
-1, we should fallback to using IAM is no key/secret is specified.

**Comment by stack72** [comment]
@analytically FWIW, I'm not reinventing the wheel here. I am using a method that is already in place here

https://github.com/sensu-plugins/sensu-plugins-aws/blob/master/bin/check-instance-events.rb#L74

This repo doesn't have a standardway of handling this

**Comment by analytically** [comment]
Yeah I realize this. We should address this plugin-wide.

**Comment by stephen-elves-tsm** [comment]
Is this going anywhere?

**Comment by analytically** [comment]
We should address this in all the scripts in this plugin. Fancy taking on the job?

**Comment by madAndroid** [comment]
Doesn't the AWS sdk automatically fall back to using IAM profiles if credentials are omitted? That's been my experience using the SDK .. I'm about to implement some of these plugins using IAM profiles exclusively, will report back on my experiences here.

**Comment by madAndroid** [comment]
It looks as though they do, from what I've seen .. I've not tested all of the plugins though - only the `check-autoscaling-cpucredits.rb` one .. but if the same SDK is in use for all of them, presumably the same applies.

**Comment by jessechahal** [comment]
I've tested this with the check-rds.rb and am currently using IAM role. This is currently working fine.

**Comment by zbintliff** [comment]
This PR is unnecessary.   If ENV['access_token'] is nil the Credential provider are smart enough to go to the next credentials location (.aws/credential, then 169.254.169.254 for instance role)

**Comment by sstarcher** [comment]
We have an existing way of doing this properly for AWS v2

https://github.com/sensu-plugins/sensu-plugins-aws/blob/master/lib/sensu-plugins-aws/common.rb

**Pull request closed without merging**
