### PR TITLE
new metric check elasticache redis & memcached

### PR DESCRIPTION
**Pull request by phoppe93**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by phoppe93** [comment]
@sstarcher please merge.

thx

**Comment by sstarcher** [comment]
Failing CI and it's weird that Github thinks you modified `bin/check-asg-instances-created.rb`

**Comment by phoppe93** [comment]
@sstarcher i nothing changed at the bin/check-asg-instances-created.rb. 

i fixed the rubocop issue

**Comment by obazoud** [comment]
This PR breaks changes metrics-elasticache.rb and it is not mentioned in changelog.
And I found a bug see #193

**Pull request merged**
