### PR TITLE
fixes #229 where default options were exploding

### LINKED ISSUE #229: check-cloudwatch-metric.rb doesn't accept absence of dimentions
`check-cloudwatch-metric.rb -r us-east-1 --namespace AWS/RDS -m DatabaseConnections -p 60 -w 5 -c 2` resulting a message:
>Check failed to run: expected params[:dimensions] to be an Array, got value “” (class: String) instead., [“/Users/suncheez/.rvm/gems/ruby-2.4.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/param_validator.rb:28:in `validate!‘”

But Json is ok about absence of dimensions (this is an aggregated metric for all RDS instances):
```
        {
            "Namespace": "AWS/RDS", 
            "Dimensions": [], 
            "MetricName": "DatabaseConnections"
        },
```

### PR DESCRIPTION
**Pull request by majormoses**
## Pull Request Checklist
#229 

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### Purpose
Prevent default dimension option from exploding
#### Known Compatibility Issues
none.

### CODE REVIEW

**Comment by majormoses** [comment]
Before fix:
```
$ bundle exec ./bin/check-cloudwatch-metric.rb -r us-east-1 --namespace AWS/RDS -m DatabaseConnections -p 60 -w 5 -c 2
Check failed to run: expected params[:dimensions] to be an Array, got value "," (class: String) instead., ["/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/param_validator.rb:28:in `validate!'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/param_validator.rb:13:in `validate!'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/seahorse/client/plugins/response_target.rb:21:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/seahorse/client/request.rb:70:in `send_request'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'", "/home/babrams/projects/personal/sensu/sensu-plugins-aws/lib/sensu-plugins-aws/cloudwatch-common.rb:87:in `check'", "./bin/check-cloudwatch-metric.rb:121:in `run'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sensu-plugin-2.1.0/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```
after fix:
```
$ bundle exec ./bin/check-cloudwatch-metric.rb -r us-west-2 --namespace AWS/RDS -m DatabaseConnections -p 60 -w 5 -c 2
CloudWatchMetricCheck CRITICAL: AWS/RDS-DatabaseConnections([]) is 6.666666666666667: comparison=greater threshold=2.0
```

**Comment by majormoses** [comment]
This actually is horribly broken....

**Comment by majormoses** [comment]
OK I fixed it this time.
no default dimension:
```
$ bundle exec ./bin/check-cloudwatch-metric.rb -r us-west-2 --namespace AWS/RDS -m DatabaseConnections -p 60 -w 5 -c 2
CloudWatchMetricCheck CRITICAL: AWS/RDS-DatabaseConnections() is 6.666666666666667: comparison=greater threshold=2.0
```

with a specified dimension:
```
$ bundle exec ./bin/check-cloudwatch-metric.rb -r us-west-2 --namespace AWS/RDS -m DatabaseConnections -d 'EngineName=mysql' -p 60 -w 5 -c 2
CloudWatchMetricCheck CRITICAL: AWS/RDS-DatabaseConnections(EngineName=mysql) is 10.0: comparison=greater threshold=2.0
```

**Comment by majormoses** [comment]
@ay-b can you try pulling my changes and see if it works for you?

**Comment by suncheez** [comment]
@majormoses new patch passed all tests. 
Thanks!

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-aws/versions/7.0.1

**Pull request merged**
