### PR TITLE
Cloudwatch composite metric for percentage computation

### PR DESCRIPTION
**Pull request by cornelf**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

- [x] Add the plugin to the README

- [x] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
Computes a percentage metric based on a couple of cloudwatch metrics, e.g. percentage of HTTPCode_Backend_4XX from the RequestCount over an observed period of time.

#### Known Compatablity Issues
None.

### CODE REVIEW

**Comment by cornelf** [comment]
@sstarcher does this PR look useful and ready according to contributions recommendations? I already have a usecase for it and it would be nice to see it going through. Thanks

**Comment by sstarcher** [comment]
Can you move your changelog entry to the unreleased section

**Comment by sstarcher** [comment]
Thanks

**Comment by cornelf** [comment]
@sstarcher  awesome!

**Pull request merged**
