### PR TITLE
Aws sdk v2

### PR DESCRIPTION
**Pull request by Yerta**
It's just an update of the check-autoscaling-cpucredit plugin in order to use the v2 of aws-sdk

### CODE REVIEW

**Comment by tas50** [comment]
Nice update. There's a few rubocop warnings to resolve before this can get merged

**Comment by analytically** [comment]
Nice indeed! Still couple of rubocop warnings..

**Comment by Yerta** [comment]
I'm not used to these tool like bundler or rake. But I will figure out.

**Comment by Yerta** [comment]
I'm looking forward to update some others plugin to the aws-sdk latest version. Would you prefer one pull request for each of them or all on the same?

**Comment by tas50** [comment]
Whatever way is easier for you

**Comment by Yerta** [comment]
Then I will push them on this branch each time one is ready.

**Comment by analytically** [comment]
Please let me know when you're done, I'll test your changes and merge the PR.

**Comment by Yerta** [comment]
I'm done. You can test these plugins. If I have the time to work on the others I'll open a new request.

**Comment by zbintliff** [comment]
I know there wasn't tests to start with but the new SDK allows for stubbing requests. It validates all input though so you will know if its a valid request or not.

**Comment by analytically** [comment]
:+1: for stubbing requests, @zbintliff mind working out an example?

**Comment by zbintliff** [comment]
Was planning on it until I remembered every thing uses auto run making it
much harder than standard testcases.

Will try to work on something this weekend

**Comment by zbintliff** [comment]
@analytically  here is an example of stubbing out requests in aws and writing tests for all these checks/handlers/etc that use auto_run #72

**Comment by analytically** [comment]
Shall we merge this?

**Comment by sstarcher** [comment]
LGTM, but it needs rebased

**Comment by analytically** [comment]
@Yerta can you rebase?

**Comment by analytically** [comment]
@Yerta please let me know when you're done, including working tests - then I'll review/merge, thanks!

**Comment by sstarcher** [comment]
@analytically those failures are related to the certs

**Comment by mattyjones** [comment]
@sstarcher  It looks that way, I am working on it now

**Comment by mattyjones** [comment]
@Yerta  Can you rebase this. We updated the certs and I believe that is what the problem is as it works fine without this pr.

Thanks!

**Comment by mattyjones** [comment]
@Yerta  @analytically When you are good with this PR I will merge it by hand. I am not sure of the issue and what is going on but I know Master is building fine. A rebase should have fixed it all. I have a feeling it is not bringing in the new certs which would cause the above error.

**Comment by analytically** [comment]
I'm good with it!

**Comment by mattyjones** [comment]
[v2.1.1](https://github.com/sensu-plugins/sensu-plugins-aws/releases/tag/v2.1.1)
@analytically @Yerta 

Thanks for all the work on this!

**Pull request merged**
