### PR TITLE
Beanstalk Health Check

### PR DESCRIPTION
**Pull request by brendangibat**

### CODE REVIEW

**Comment by analytically** [comment]
@mattyjones seems like the cert issues persist?

**Comment by mattyjones** [comment]
@analytically That may be the case with old PR's I am attempting to clear some PR's when I can as I go through this. I am not sure why they persist if a rebase was done. It makes no sense to me. If I do a manual merge and rebase everything is fine.

@brendangibat Can you or did you do a rebase within the last 24 hours. I have one 
other thing I think may be suspect I will try out.

I have a feeling Travis is not expanding out the keys on insecure pulls so they are all going to fail. I will open up a few PR's in a few to test out this theory. If thats the case then I will figure out a work around for this.

**Comment by sstarcher** [comment]
@mattyjones The PR itself is actually new as he closed his old PR and opened this.

**Comment by brendangibat** [comment]
@mattyjones I based off of master yesterday evening after closing a previous PR, and I just did a rebase that gave no changes.

**Comment by mattyjones** [comment]
Then the issue is most likely due to how I have Travis configured and the fact that a PR is considered an insecure build. I will dig into this today at some point.

**Comment by sstarcher** [comment]
rubocop
```
bin/check-beanstalk-health.rb:35:1: C: Extra empty line detected at class body beginning.
bin/check-beanstalk-health.rb:37:9: C: Align the parameters of a method call if they span more than one line.
        description: 'Application environment name',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:43:9: C: Align the parameters of a method call if they span more than one line.
        short: '-n',
        ^^^^^^^^^^^^
bin/check-beanstalk-health.rb:51:7: C: Align .describe_environment_health with beanstalk_client on line 50.
      .describe_environment_health({
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:51:36: C: Redundant curly braces around a hash parameter.
      .describe_environment_health({
                                   ^
bin/check-beanstalk-health.rb:52:11: C: Use 2 spaces for indentation in a hash, relative to the first position after the preceding left parenthesis.
          environment_name: config[:environment],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:53:28: C: Use %w or %W for an array of words.
          attribute_names: ["Color", "Status", "HealthStatus", "Causes"]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:53:29: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
          attribute_names: ["Color", "Status", "HealthStatus", "Causes"]
                            ^^^^^^^
bin/check-beanstalk-health.rb:53:38: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
          attribute_names: ["Color", "Status", "HealthStatus", "Causes"]
                                     ^^^^^^^^
bin/check-beanstalk-health.rb:53:48: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
          attribute_names: ["Color", "Status", "HealthStatus", "Causes"]
                                               ^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:53:64: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
          attribute_names: ["Color", "Status", "HealthStatus", "Causes"]
                                                               ^^^^^^^^
bin/check-beanstalk-health.rb:54:11: C: Indent the right brace the same as the first position after the preceding left parenthesis.
          })
          ^
bin/check-beanstalk-health.rb:63:67: C: Redundant curly braces around a hash parameter.
      curr_instances = beanstalk_client.describe_instances_health({
                                                                  ^
bin/check-beanstalk-health.rb:64:9: C: Use 2 spaces for indentation in a hash, relative to the first position after the preceding left parenthesis.
        environment_name: config[:environment],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:65:26: C: Use %w or %W for an array of words.
        attribute_names: ["Color", "HealthStatus", "Causes"]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:65:27: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
        attribute_names: ["Color", "HealthStatus", "Causes"]
                          ^^^^^^^
bin/check-beanstalk-health.rb:65:36: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
        attribute_names: ["Color", "HealthStatus", "Causes"]
                                   ^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:65:52: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
        attribute_names: ["Color", "HealthStatus", "Causes"]
                                                   ^^^^^^^^
bin/check-beanstalk-health.rb:66:9: C: Indent the right brace the same as the first position after the preceding left parenthesis.
        })
        ^
bin/check-beanstalk-health.rb:68:7: C: Favor until over while for negative conditions.
      while !curr_instances.next_token.nil?
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:69:69: C: Redundant curly braces around a hash parameter.
        curr_instances = beanstalk_client.describe_instances_health({
                                                                    ^
bin/check-beanstalk-health.rb:70:11: C: Use 2 spaces for indentation in a hash, relative to the first position after the preceding left parenthesis.
          environment_name: config[:environment],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:71:28: C: Use %w or %W for an array of words.
          attribute_names: ["Color", "HealthStatus", "Causes"]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:71:29: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
          attribute_names: ["Color", "HealthStatus", "Causes"]
                            ^^^^^^^
bin/check-beanstalk-health.rb:71:38: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
          attribute_names: ["Color", "HealthStatus", "Causes"]
                                     ^^^^^^^^^^^^^^
bin/check-beanstalk-health.rb:71:54: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
          attribute_names: ["Color", "HealthStatus", "Causes"]
                                                     ^^^^^^^^
bin/check-beanstalk-health.rb:72:11: C: Indent the right brace the same as the first position after the preceding left parenthesis.
          })
          ^
bin/check-beanstalk-health.rb:80:54: C: Space between { and | missing.
    @unhealthy_instances ||= instances_health.select {|i| i.color != "Green"}
                                                     ^^
bin/check-beanstalk-health.rb:80:70: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    @unhealthy_instances ||= instances_health.select {|i| i.color != "Green"}
                                                                     ^^^^^^^
bin/check-beanstalk-health.rb:80:77: C: Space missing inside }.
    @unhealthy_instances ||= instances_health.select {|i| i.color != "Green"}
                                                                            ^
bin/check-beanstalk-health.rb:84:123: C: Prefer single-quoted strings inside interpolations.
    "Beanstalk Status: #{env_health.status}, Health Status: #{env_health.health_status}, Causes: #{env_health.causes.join(", ")}"
                                                                                                                          ^^^^
bin/check-beanstalk-health.rb:88:144: C: Prefer single-quoted strings inside interpolations.
    "instance id: #{instance.instance_id}, color: #{instance.color}, health status: #{instance.health_status}, causes: [#{instance.causes.join(", ")}]"
                                                                                                                                               ^^^^
bin/check-beanstalk-health.rb:92:69: C: Space missing to the left of {.
    "Unhealthy instances and causes: [ #{unhealthy_instances.collect{|i| unhealthy_instance_description(i)}.join(", ")} ]"
                                                                    ^
bin/check-beanstalk-health.rb:92:69: C: Space between { and | missing.
    "Unhealthy instances and causes: [ #{unhealthy_instances.collect{|i| unhealthy_instance_description(i)}.join(", ")} ]"
                                                                    ^^
bin/check-beanstalk-health.rb:92:107: C: Space missing inside }.
    "Unhealthy instances and causes: [ #{unhealthy_instances.collect{|i| unhealthy_instance_description(i)}.join(", ")} ]"
                                                                                                          ^
bin/check-beanstalk-health.rb:92:114: C: Prefer single-quoted strings inside interpolations.
    "Unhealthy instances and causes: [ #{unhealthy_instances.collect{|i| unhealthy_instance_description(i)}.join(", ")} ]"
                                                                                                                 ^^^^
bin/check-beanstalk-health.rb:97:17: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    if color == "Green"
                ^^^^^^^
bin/check-beanstalk-health.rb:99:20: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    elsif color == "Yellow"
                   ^^^^^^^^
bin/check-beanstalk-health.rb:101:20: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    elsif color == "Red"
                   ^^^^^
bin/check-beanstalk-health.rb:103:20: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
    elsif color == "Grey"
                   ^^^^^^
```

**Pull request closed without merging**
