### PR TITLE
Migrating check-elb-nodes to fog

### PR DESCRIPTION
**Pull request by pablokbs**
With fog we can now use IAM Roles, classic key/secret method is still supported

### CODE REVIEW

**Comment by mattyjones** [comment]
I would prefer to use the aws-sdk unless you have a good reason not to?

**Comment by pablokbs** [comment]
Because aws-sdk doesn't support iam roles, I believe.

**Comment by mattyjones** [comment]
@pablokbs  http://docs.aws.amazon.com/sdkforruby/api/Aws/IAM.html

**Comment by sstarcher** [comment]
@pablokbs I would recommend doing similar to 
https://github.com/sstarcher/sensu-plugins-aws/commit/8b5768152d0909176e6f766bbce47cf923aac5d5

If you bump it to aws-sdk v2 you can use the common module I added to do the credential work.

**Comment by tas50** [comment]
We're in the process of migrating these checks all to the v2 ruby gem.  It's preferred that we use the official amazon gem for these since it's fairly dep free and officially supported at this point.

**Pull request closed without merging**
