### PR TITLE
state_reason may not be defined by the API response

### PR DESCRIPTION
**Pull request by WrathOfChris**
## Pull Request Checklist

**Is this in reference to an existing issue?**

No.

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### Purpose

Protect against nil instance `state_reason`.

### CODE REVIEW

**Comment by analytically** [comment]
Can you fix bin/handler-ec2_node.rb:172:69: C: Prefer the use of the nil? predicate.

**Comment by eheydrick** [comment]
@WrathOfChris bump for rubocop issues and we'll get this merged.

**Comment by WrathOfChris** [comment]
Hey, thanks, have been travelling, will re-submit in next few days.

**Comment by analytically** [comment]
Can you rebase?

**Comment by WrathOfChris** [comment]
sure, rebased.

**Comment by eheydrick** [comment]
Thanks @WrathOfChris!

**Pull request merged**
