### PR TITLE
Add exlude tags option

### PR DESCRIPTION
**Pull request by obazoud**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by eheydrick** [comment]
Hi @obazoud, thanks for this. Can you take a look at the rubocop errors.

**Comment by eheydrick** [comment]
Bump @obazoud

**Comment by obazoud** [comment]
Rubocop errors fixed and commits squashed @eheydrick

**Comment by eheydrick** [comment]
Thanks @obazoud.

**Pull request merged**
